### ISSUE TITLE
IMPORTANT

### ISSUE THREAD

**Issue by mstf026** [hakanyilmazz/Demon-Slayer---Zenitsu-Agatsuma-Effect--Unity-Game-#1]
Hello,
I am here to discuss some important things about the path we shall follow
Have a nice day

**Comment by hakanyilmazz** [comment]
Hello,
Dear Mustafa, ofcourse we can talk about that. Firstly you should send me the teams invitation link.
Best Regards. Hakan.

**Comment by hakanyilmazz** [comment]
Wait i already have the link. Don't send please. I'm waiting for you in teams chat.

**Comment by mstf026** [comment]
![image](https://github.com/hakanyilmazz/Demon-Slayer---Zenitsu-Agatsuma-Effect--Unity-Game-/assets/127982678/9c07724a-850c-4e84-9eed-666168cfe009)

**Comment by mstf026** [comment]
![giphy](https://github.com/hakanyilmazz/Demon-Slayer---Zenitsu-Agatsuma-Effect--Unity-Game-/assets/127982678/5ad28cbe-f72f-4ccd-9cc1-cc741ef9b26d)
